# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoursquareClientSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Swinject'
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'AlamofireObjectMapper', '~> 5.0'
end
